nama = input("Nama Anda: ")
alamat = input("Alamat Tinggal Anda: ")
umur = input("Umur Anda: ")
tl = input("Tempat Lahir Anda: ")
tgl = input("Tanggal Lahir Anda: ")
ipk = input("IPK Anda: ")
print("========================================")
print("DATA AKADEMIK")
print("Nama Anda: ", nama)
print("Alamat Tinggal Anda:", alamat)
print("Umur Anda:", umur)
print("Tempat Anda:", tl)
print("Tahun Lahir Anda:", tgl)
print("IPK Anda:", ipk)
